-- MySQL Script generated by MySQL Workbench
-- dom 22 nov 2020 17:26:56 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb_Catastro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_Catastro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_Catastro` DEFAULT CHARACTER SET utf8 ;
USE `mydb_Catastro` ;

-- -----------------------------------------------------
-- Table `mydb_Catastro`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`Zona` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Área` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb_Catastro`.`Calle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`Calle` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Zona_Nombre` VARCHAR(45) NOT NULL,
  `Nº Carriles` INT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Longitud` FLOAT NULL,
  PRIMARY KEY (`Nombre`),
  -- INDEX `fk_Calle_Zona_idx` (`Zona_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Calle_Zona`
    FOREIGN KEY (`Zona_Nombre`)
    REFERENCES `mydb_Catastro`.`Zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb_Catastro`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`Bloque` (
  `Numero` INT NOT NULL,
  `Superficie` FLOAT NULL,
  `Año` DATE NULL,
  `Calle_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Numero`, `Calle_Nombre`),
  -- INDEX `fk_Bloque_Calle1_idx` (`Calle_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Bloque_Calle1`
    FOREIGN KEY (`Calle_Nombre`)
    REFERENCES `mydb_Catastro`.`Calle` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb_Catastro`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`Piso` (
  `Letra` VARCHAR(2) NOT NULL,
  `Planta` INT NOT NULL,
  `Bloque_Numero` INT NOT NULL,
  `Bloque_Calle_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Letra`, `Planta`, `Bloque_Numero`, `Bloque_Calle_Nombre`),
  -- INDEX `fk_Piso_Bloque1_idx` (`Bloque_Número` ASC, `Bloque_Calle_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Piso_Bloque1`
    FOREIGN KEY (`Bloque_Numero` , `Bloque_Calle_Nombre`)
    REFERENCES `mydb_Catastro`.`Bloque` (`Numero` , `Calle_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb_Catastro`.`Unifamiliares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`Unifamiliares` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Superficie` FLOAT NULL,
  `Año` DATE NULL,
  `Nº habitantes` INT NULL,
  `Calle_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `Calle_Nombre`),
  -- INDEX `fk_Unifamiliares_Calle1_idx` (`Calle_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Unifamiliares_Calle1`
    FOREIGN KEY (`Calle_Nombre`)
    REFERENCES `mydb_Catastro`.`Calle` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb_Catastro`.`Personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`Personas` (
  `DNI` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Piso_Letra` VARCHAR(2) NOT NULL,
  `Piso_Planta` INT NOT NULL,
  `Piso_Bloque_Numero` INT NOT NULL,
  `Piso_Bloque_Calle_Nombre` VARCHAR(45) NOT NULL,
  `Unifamiliares_Nombre` VARCHAR(45) NOT NULL,
  `Unifamiliares_Calle_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`),
  -- INDEX `fk_Personas_Piso1_idx` (`Piso_Letra` ASC, `Piso_Planta` ASC, `Piso_Bloque_Número` ASC, `Piso_Bloque_Calle_Nombre` ASC) VISIBLE,
  -- INDEX `fk_Personas_Unifamiliares1_idx` (`Unifamiliares_Nombre` ASC, `Unifamiliares_Calle_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Personas_Piso1`
    FOREIGN KEY (`Piso_Letra` , `Piso_Planta` , `Piso_Bloque_Numero` , `Piso_Bloque_Calle_Nombre`)
    REFERENCES `mydb_Catastro`.`Piso` (`Letra` , `Planta` , `Bloque_Numero` , `Bloque_Calle_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personas_Unifamiliares1`
    FOREIGN KEY (`Unifamiliares_Nombre` , `Unifamiliares_Calle_Nombre`)
    REFERENCES `mydb_Catastro`.`Unifamiliares` (`Nombre` , `Calle_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- ------------
-- EJERCICIO 2
-- ------------

DELIMITER $$
USE `mydb_Catastro`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb_Catastro`.`trigger_solounavivienda_BEFORE_INSERT` BEFORE INSERT ON `Personas` FOR EACH ROW
BEGIN
  IF ((NEW.Unifamiliares_Nombre is NOT NULL)&& (NEW.Piso_Bloque_Numero is NOT NULL)) THEN
    SIGNAL SQLSTATE 'ERROR' SET MESSAGE_TEXT = 'una persona no puede vivir en dos lugares a la vez';
  END IF;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;